In [3]:
import torch
import numpy as np

In [23]:
X = torch.randn(100,10)
y = X*2 + torch.abs(X)
m = torch.mean(X)
print(m)
m_value = m.item()
print(m_value)
m2 = X.mean(0)
m3 = m2.mean()
print(m3)

tensor(-0.0294)
-0.02936793677508831
tensor(-0.0294)


In [35]:
x1 = torch.tensor([[1,2],[3,4]])
x1.view(4,1)
x1.t()
x2 = torch.tensor([[10,20,30],[40,50,60]])
print(x1)
print(x2)
torch.cat([x1,x2],dim=1) 

tensor([[1, 2],
        [3, 4]])
tensor([[10, 20, 30],
        [40, 50, 60]])


tensor([[ 1,  2, 10, 20, 30],
        [ 3,  4, 40, 50, 60]])

In [41]:
x = torch.randn(100,3)
print(x)
a = torch.tensor([1.,2.,3.],requires_grad = True)
y = torch.mv(x,a)
o = y.sum()
o.backward()
a.grad != x.sum(0)

tensor([[ 1.4352,  1.5853,  0.3427],
        [-1.3788, -0.5347, -0.5633],
        [ 0.1140,  1.4923, -0.3796],
        [-1.6006, -0.3041, -1.1747],
        [ 0.4019, -1.3041,  0.2628],
        [ 0.2896, -0.6782, -0.8780],
        [-1.4383,  1.0518,  0.3715],
        [-0.9405,  0.3775, -0.5934],
        [-0.0455,  0.7263,  0.7395],
        [ 1.5602, -0.9919, -0.8437],
        [ 0.3343,  1.1200,  1.5550],
        [ 0.6581, -0.8313, -0.7132],
        [ 0.8293,  0.1345,  0.9281],
        [-0.8191, -0.3322, -0.7826],
        [ 0.1774, -0.3804,  2.3411],
        [-1.4921, -0.4742,  0.5350],
        [ 0.6626,  1.2319,  0.7501],
        [-0.2948,  0.3240, -0.3461],
        [ 1.7536, -0.7247,  1.1010],
        [ 0.6689,  0.6046,  0.8649],
        [-0.9462, -1.4249, -2.6972],
        [-0.0560,  1.0392, -0.3375],
        [-1.9660, -0.8613, -1.3393],
        [ 1.2419,  0.0855,  0.5880],
        [-1.0933,  1.1081,  0.3746],
        [ 1.4154, -0.1457,  0.5597],
        [ 0.8814, -2.3242, -0.5809],
 

tensor([ True,  True, False])

In [64]:
import torch
from torch import nn,optim
w_true = torch.Tensor([1,2,3])
X = torch.cat([torch.ones(100, 1), torch.randn(100, 2)],dim=1)
#print(X)
y = torch.mv(X,w_true) + torch.randn(100)*0.5
w = torch.randn(3,requires_grad=True)
gamma = 0.1

losses = []
for epoc in range(100):
    w.grad = None
    y_pred = torch.mv(X,w)
    loss = torch.mean((y-y_pred)**2)
    loss.backward()
    w.data = w.data - gamma*w.grad.data
    losses.append(loss.item())
print(losses)

losses = []
net = nn.Linear(in_features=3,out_features=1,bias=False)
optimizer = optim.SGD(net.parameters(),lr=0.1)
loss_fn = nn.MSELoss()
for epoc in range(100):
    optimizer.zero_grad()
    y_pred = net(X)
    loss = loss_fn(y_pred.view_as(y),y)
    loss.backward()
    optimizer.step()
    losses.append(loss.item())
print(losses)

[10.317970275878906, 6.326066970825195, 3.9627137184143066, 2.5481162071228027, 1.6913853883743286, 1.1660758256912231, 0.8398821949958801, 0.6347579956054688, 0.50417160987854, 0.4200599193572998, 0.36529141664505005, 0.32927557826042175, 0.3053820729255676, 0.2894079387187958, 0.2786569893360138, 0.2713802754878998, 0.26643142104148865, 0.2630522847175598, 0.2607373595237732, 0.25914713740348816, 0.25805240869522095, 0.2572973370552063, 0.25677579641342163, 0.25641506910324097, 0.25616535544395447, 0.25599244236946106, 0.25587254762649536, 0.2557893395423889, 0.2557316720485687, 0.2556915879249573, 0.25566378235816956, 0.25564444065093994, 0.25563108921051025, 0.2556217610836029, 0.2556152641773224, 0.25561076402664185, 0.25560763478279114, 0.2556054890155792, 0.25560396909713745, 0.2556028664112091, 0.2556021809577942, 0.2556016743183136, 0.25560134649276733, 0.25560104846954346, 0.2556008994579315, 0.25560081005096436, 0.2556006908416748, 0.2556006610393524, 0.25560063123703003, 0.

In [72]:
x = torch.randn(2,3)
x.view(1,-1)


tensor([[ 0.6828, -1.2435,  0.1053,  1.0128,  0.4747,  0.5576]])